### ISSUE TITLE
Just kind of curious, how well is emacs performing?

### ISSUE THREAD

**Issue by claford-v-lawrence** [revrari/install-emacs-windows#1]
I tried to install emacs on windows just the other day but found that it was much much slower than on linux, so I was wondering how's your new emacs performing with the new native json support?

**Comment by revrari** [comment]
It is my experience that Emacs on Windows is always slower. The solution to this is to use Emacsclient. If set up correctly Emacs on Windows will start up very quickly.

**Comment by claford-v-lawrence** [comment]
Thanks for your information!
